services:
  instance:
    image: dfxyz/archlinux
    hostname: dfxyz-archlinux-in-docker
    restart: unless-stopped
    command: ["-"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
volumes:
  data: {}

